project:
  type: website

website:
  title: "Howard Baek"
  favicon: favicon.png
  navbar:
    right:
      - about.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/howardbaek
      - icon: twitter
        href: https://twitter.com/howard_baek
format:
  html:
    theme: litera
    css: styles.css

editor: visual

execute:
  freeze: auto

