project:
  type: website

website:
  title: "Howard Baek"
  site-url: "https://howardbaek.com/"
  favicon: favicon.png
  navbar:
    right:
      - about.qmd
      - blog.qmd
      - projects.qmd
      - icon: github
        href: https://github.com/howardbaek
      - icon: twitter
        href: https://twitter.com/howard_baek
  page-footer:
    left: |
      Powered by [Quarto](https://quarto.org)
    border: false
format:
  html:
    theme: litera
    css: styles.css

editor: visual

execute:
  freeze: auto

